apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: dev
spec:
  externalTrafficPolicy: Local
  type: NodePort
  ports:
  - port: 9090
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: echo-server